/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {
    private static final List<Integer> INPUT = List.of(17, 56);
    App classUnderTest;

    @BeforeEach
    void createSubject() {
        classUnderTest = new App(INPUT);
    }

    @Test void part1ReturnsFirstAsString() {
        assertEquals("17", classUnderTest.getSolutionPart1());
    }

    @Test void part2ReturnsSecondAsString() {
        assertEquals("56", classUnderTest.getSolutionPart2());
    }
}
