/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aoc;

public class App {
    public String getSolutionPart1() {
        return "1337";
    }

    public String getSolutionPart2() {
        return "42";
    }

    public static void main(String[] args) {
        String part = System.getenv("part") == null ? "part1" : System.getenv("part");
        if (part.equals("part1"))
            System.out.println(new App().getSolutionPart1());
        else
            System.out.println(new App().getSolutionPart2());
    }
}
